In [1]:
import numpy as np
#optimization written in C
#Vectorization via broadcasting(avoiding loops)
#backbone of scientific packages

### datatypes and attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
             [4,5,6]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [8]:
scale = (lambda x:x+x)
scale(a1)

array([2, 4, 6])